# Generated by Django 2.1 on 2019-03-05 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=12)),
                ('password', models.CharField(default='None', max_length=100)),
                ('nick_name', models.CharField(default='None', max_length=100)),
                ('face_data_file', models.FileField(default='None', upload_to='userfeature')),
                ('picture', models.ImageField(default='None', upload_to='userimg')),
                ('email', models.EmailField(default='None', max_length=254)),
                ('phone_number', models.CharField(default='None', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsystem.Order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserLogin.User', verbose_name='订单用户')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuck', to='UserLogin.User', verbose_name='其他与会人员'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserLogin.User', verbose_name='预定人'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsystem.Order', verbose_name='订单'),
        ),
    ]
