# Generated by Django 2.1.7 on 2019-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0002_meeting_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='join_remark',
            field=models.CharField(default='None', max_length=32, verbose_name='加入备注'),
        ),
    ]
