# Generated by Django 2.1 on 2019-03-05 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(default='None', max_length=32, verbose_name='会议室房间号')),
                ('room_type', models.CharField(default='None', max_length=32, verbose_name='会议室类型')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_time', models.DateTimeField(auto_now=True, verbose_name='订单创建时间')),
                ('booking_date', models.DateField(verbose_name='订单日期')),
                ('remark', models.CharField(default='None', max_length=32, verbose_name='备注')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsystem.MeetingRoom', verbose_name='会议室')),
            ],
        ),
    ]
