# Generated by Django 2.1 on 2019-03-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='content',
            field=models.IntegerField(default=40, verbose_name='会议室容量'),
        ),
    ]
