# Generated by Django 2.1 on 2019-03-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsystem', '0002_meetingroom_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='img',
            field=models.ImageField(default='None', upload_to='room_img'),
        ),
    ]
