# Generated by Django 2.1 on 2019-03-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsystem', '0003_meetingroom_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='img',
            field=models.FileField(default='None', upload_to='room_img'),
        ),
    ]
